[package]
name = "uk-property-search-data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive"] }
config = "0.13.1"
futures = "0.3.21"
itertools = "0.10.3"
mongodb = { version = "2.2.1", features = ["bson-chrono-0_4"] }
polars = { version = "0.21.1"}
reqwest = "0.11.10"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.18.2", features = ["sync"] }
