[db]
mongo.uri = "mongodb+srv://uk-property-search:5HUA2zBnKnlUVhpt@cluster0.4kpiz.mongodb.net"
mongo.name = "uk-property-search"

[http]
max.parallel.connections = 50
max.retry.count = 3

[log]
level = "info"

[rightmove]
max.parallel.connections = 10

[server]
default.port = 3000