[db]
mongo.name = "uk-property-search"
mongo.uri = "mongodb+srv://uk-property-search:5HUA2zBnKnlUVhpt@cluster0.4kpiz.mongodb.net"

[http]
max.parallel.connections = 50
max.retry.count = 3

[log]
level = "info"

[propertylog]
max.parallel.connections = 5
max.retry.count = 100
retry.delay.seconds = 30
user = "x2bgwbbphpjkxzkn"

[rightmove]
max.parallel.connections = 5

[server]
default.port = 3000
